mqtt_broker_address: 192.168.131.214
mqtt_broker_port: 1883
mqtt_data_path: C:/Users/me1elar/Documents/GitHub/tcpip_mqtt_clients/data/mqtt
mqtt_topic: ORA/v1/instrument/measurements/Static.Constellation->Spindle.SMR
tcpip_address: 172.16.49.197
tcpip_data_path: C:/Users/me1elar/Documents/GitHub/tcpip_mqtt_clients/data/tcpip
tcpip_port_number: 5000
